steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/guesslyfe/guessly-backend:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/guesslyfe/guessly-backend:latest'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/guesslyfe/guessly-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/guesslyfe/guessly-backend:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        # Extract environment variables from .env.production and create --update-env-vars format
        ENV_VARS=$(cat backend/.env.production | grep -v '^#' | grep -v '^$' | awk -F= '{printf "%s=%s,",$1,$2}' | sed 's/,$//')

        # Deploy to Cloud Run with inline environment variables
        gcloud run deploy guessly-backend \
          --image us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/guesslyfe/guessly-backend:$COMMIT_SHA \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --port 8080 \
          --timeout 600 \
          --max-instances 10 \
          --memory 2Gi \
          --update-env-vars "$ENV_VARS"

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/guesslyfe/guessly-backend:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/guesslyfe/guessly-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY

# Cloud Build trigger configuration
timeout: '3600s'
