FROM node:18

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy source code
COPY . .

# Build
RUN npm run build

# Set NODE_ENV
ENV NODE_ENV=production

# Run migrations
CMD ["npm", "run", "migration:run"]
