/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CreatorShareFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "VOLUME_THRESHOLD"
      | "addMarketContract"
      | "allCreatorShares"
      | "canCreateShares"
      | "createCreatorShares"
      | "creatorShareContract"
      | "creatorTotalVolume"
      | "getAllCreatorShares"
      | "getCreatorShareAtIndex"
      | "getCreatorShareContract"
      | "getCreatorVolume"
      | "getRemainingVolumeToUnlock"
      | "getTotalCreatorShares"
      | "isMarketWhitelisted"
      | "isSharesUnlocked"
      | "owner"
      | "removeMarketContract"
      | "renounceOwnership"
      | "sharesUnlocked"
      | "transferOwnership"
      | "updateCreatorVolume"
      | "usdc"
      | "whitelistedMarkets"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MarketContractAdded"
      | "MarketContractRemoved"
      | "OwnershipTransferred"
      | "SharesCreated"
      | "SharesUnlocked"
      | "VolumeUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "VOLUME_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addMarketContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allCreatorShares",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canCreateShares",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createCreatorShares",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorShareContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorTotalVolume",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllCreatorShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorShareAtIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorShareContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorVolume",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingVolumeToUnlock",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCreatorShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isMarketWhitelisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSharesUnlocked",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeMarketContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sharesUnlocked",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCreatorVolume",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "whitelistedMarkets",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "VOLUME_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addMarketContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allCreatorShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canCreateShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCreatorShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorShareContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorTotalVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllCreatorShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorShareAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorShareContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingVolumeToUnlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCreatorShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isMarketWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSharesUnlocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeMarketContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sharesUnlocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCreatorVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "whitelistedMarkets",
    data: BytesLike
  ): Result;
}

export namespace MarketContractAddedEvent {
  export type InputTuple = [
    marketContract: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [marketContract: string, timestamp: bigint];
  export interface OutputObject {
    marketContract: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketContractRemovedEvent {
  export type InputTuple = [
    marketContract: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [marketContract: string, timestamp: bigint];
  export interface OutputObject {
    marketContract: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesCreatedEvent {
  export type InputTuple = [
    creator: AddressLike,
    shareContract: AddressLike,
    name: string,
    symbol: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    shareContract: string,
    name: string,
    symbol: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    creator: string;
    shareContract: string;
    name: string;
    symbol: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesUnlockedEvent {
  export type InputTuple = [
    creator: AddressLike,
    finalVolume: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    finalVolume: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    creator: string;
    finalVolume: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VolumeUpdatedEvent {
  export type InputTuple = [
    creator: AddressLike,
    additionalVolume: BigNumberish,
    newTotalVolume: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    additionalVolume: bigint,
    newTotalVolume: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    creator: string;
    additionalVolume: bigint;
    newTotalVolume: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CreatorShareFactory extends BaseContract {
  connect(runner?: ContractRunner | null): CreatorShareFactory;
  waitForDeployment(): Promise<this>;

  interface: CreatorShareFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  VOLUME_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  addMarketContract: TypedContractMethod<
    [market: AddressLike],
    [void],
    "nonpayable"
  >;

  allCreatorShares: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  canCreateShares: TypedContractMethod<
    [creator: AddressLike],
    [[boolean, string] & { canCreate: boolean; reason: string }],
    "view"
  >;

  createCreatorShares: TypedContractMethod<
    [creator: AddressLike, name: string, symbol: string],
    [string],
    "nonpayable"
  >;

  creatorShareContract: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  creatorTotalVolume: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  getAllCreatorShares: TypedContractMethod<[], [string[]], "view">;

  getCreatorShareAtIndex: TypedContractMethod<
    [index: BigNumberish],
    [string],
    "view"
  >;

  getCreatorShareContract: TypedContractMethod<
    [creator: AddressLike],
    [string],
    "view"
  >;

  getCreatorVolume: TypedContractMethod<
    [creator: AddressLike],
    [bigint],
    "view"
  >;

  getRemainingVolumeToUnlock: TypedContractMethod<
    [creator: AddressLike],
    [bigint],
    "view"
  >;

  getTotalCreatorShares: TypedContractMethod<[], [bigint], "view">;

  isMarketWhitelisted: TypedContractMethod<
    [market: AddressLike],
    [boolean],
    "view"
  >;

  isSharesUnlocked: TypedContractMethod<
    [creator: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  removeMarketContract: TypedContractMethod<
    [market: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sharesUnlocked: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateCreatorVolume: TypedContractMethod<
    [creator: AddressLike, additionalVolume: BigNumberish],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  whitelistedMarkets: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "VOLUME_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addMarketContract"
  ): TypedContractMethod<[market: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allCreatorShares"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "canCreateShares"
  ): TypedContractMethod<
    [creator: AddressLike],
    [[boolean, string] & { canCreate: boolean; reason: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCreatorShares"
  ): TypedContractMethod<
    [creator: AddressLike, name: string, symbol: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "creatorShareContract"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "creatorTotalVolume"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllCreatorShares"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getCreatorShareAtIndex"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getCreatorShareContract"
  ): TypedContractMethod<[creator: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getCreatorVolume"
  ): TypedContractMethod<[creator: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRemainingVolumeToUnlock"
  ): TypedContractMethod<[creator: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalCreatorShares"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isMarketWhitelisted"
  ): TypedContractMethod<[market: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isSharesUnlocked"
  ): TypedContractMethod<[creator: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeMarketContract"
  ): TypedContractMethod<[market: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sharesUnlocked"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateCreatorVolume"
  ): TypedContractMethod<
    [creator: AddressLike, additionalVolume: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "whitelistedMarkets"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "MarketContractAdded"
  ): TypedContractEvent<
    MarketContractAddedEvent.InputTuple,
    MarketContractAddedEvent.OutputTuple,
    MarketContractAddedEvent.OutputObject
  >;
  getEvent(
    key: "MarketContractRemoved"
  ): TypedContractEvent<
    MarketContractRemovedEvent.InputTuple,
    MarketContractRemovedEvent.OutputTuple,
    MarketContractRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SharesCreated"
  ): TypedContractEvent<
    SharesCreatedEvent.InputTuple,
    SharesCreatedEvent.OutputTuple,
    SharesCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SharesUnlocked"
  ): TypedContractEvent<
    SharesUnlockedEvent.InputTuple,
    SharesUnlockedEvent.OutputTuple,
    SharesUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "VolumeUpdated"
  ): TypedContractEvent<
    VolumeUpdatedEvent.InputTuple,
    VolumeUpdatedEvent.OutputTuple,
    VolumeUpdatedEvent.OutputObject
  >;

  filters: {
    "MarketContractAdded(address,uint256)": TypedContractEvent<
      MarketContractAddedEvent.InputTuple,
      MarketContractAddedEvent.OutputTuple,
      MarketContractAddedEvent.OutputObject
    >;
    MarketContractAdded: TypedContractEvent<
      MarketContractAddedEvent.InputTuple,
      MarketContractAddedEvent.OutputTuple,
      MarketContractAddedEvent.OutputObject
    >;

    "MarketContractRemoved(address,uint256)": TypedContractEvent<
      MarketContractRemovedEvent.InputTuple,
      MarketContractRemovedEvent.OutputTuple,
      MarketContractRemovedEvent.OutputObject
    >;
    MarketContractRemoved: TypedContractEvent<
      MarketContractRemovedEvent.InputTuple,
      MarketContractRemovedEvent.OutputTuple,
      MarketContractRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SharesCreated(address,address,string,string,uint256)": TypedContractEvent<
      SharesCreatedEvent.InputTuple,
      SharesCreatedEvent.OutputTuple,
      SharesCreatedEvent.OutputObject
    >;
    SharesCreated: TypedContractEvent<
      SharesCreatedEvent.InputTuple,
      SharesCreatedEvent.OutputTuple,
      SharesCreatedEvent.OutputObject
    >;

    "SharesUnlocked(address,uint256,uint256)": TypedContractEvent<
      SharesUnlockedEvent.InputTuple,
      SharesUnlockedEvent.OutputTuple,
      SharesUnlockedEvent.OutputObject
    >;
    SharesUnlocked: TypedContractEvent<
      SharesUnlockedEvent.InputTuple,
      SharesUnlockedEvent.OutputTuple,
      SharesUnlockedEvent.OutputObject
    >;

    "VolumeUpdated(address,uint256,uint256,uint256)": TypedContractEvent<
      VolumeUpdatedEvent.InputTuple,
      VolumeUpdatedEvent.OutputTuple,
      VolumeUpdatedEvent.OutputObject
    >;
    VolumeUpdated: TypedContractEvent<
      VolumeUpdatedEvent.InputTuple,
      VolumeUpdatedEvent.OutputTuple,
      VolumeUpdatedEvent.OutputObject
    >;
  };
}
